name: video_shader
description: A Flutter project to manage shader with camera.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=3.7.7"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image_16_9.jpg
